---
# CI build for zerotape
#

name: zerotape
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu build",  os: "ubuntu-latest",  install: "sudo apt-get install cmake ninja-build", generator: "-G Ninja", testexe: "./platform/generic/zerotape-tests ../test.zt"             }
          - { name: "Windows build", os: "windows-latest", install: "choco install cmake",                    generator: "",         testexe: "platform\\generic\\Debug\\zerotape-tests.exe ..\\test.zt" }
          - { name: "macOS build",   os: "macos-latest",   install: "brew install cmake ninja",               generator: "-G Ninja", testexe: "./platform/generic/zerotape-tests ../test.zt"             }
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.config.install }}
      - run: |
          mkdir build
          cd build
          cmake ${{ matrix.config.generator }} ..
          cmake --build .
          ${{ matrix.config.testexe }}
  build-riscos:
    name: RISC OS build
    container: riscosdotinfo/riscos-gccsdk-4.7:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cross compile zerotape
        run: |
          apt-get update
          apt-get install -y ca-certificates
          ./build-riscos.sh
