---
# CI build for zerotape
#

name: zerotape
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu build",  os: "ubuntu-latest",  install: "sudo apt-get install cmake ninja-build", generator: "-G Ninja", testexe: "./platform/generic/zerotape-tests"            }
          - { name: "Windows build", os: "windows-latest", install: "choco install cmake",                    generator: "",         testexe: "platform\\generic\\Debug\\zerotape-tests.exe" }
          - { name: "macOS build",   os: "macos-latest",   install: "brew install cmake ninja",               generator: "-G Ninja", testexe: "./platform/generic/zerotape-tests"            }
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.config.install }}
      - run: |
          mkdir build
          cd build
          cmake ${{ matrix.config.generator }} ..
          cmake --build .
          ${{ matrix.config.testexe }}
